version: 2.1
ESTE COMMIT HA SIDO ROTO POR JUAN, CULPEN A JUAN
orbs:
  maven: circleci/maven@1.4.1
executors:
  java17:
    docker:
      - image: 'cimg/openjdk:17.0'
jobs:
  say-hello:
     docker:
      - image: cimg/base:stable
     steps:
      - checkout 
      - run: ESTE COMMIT HA SIDO ROTO POR JUAN, CULPEN A JUAN
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  maven_test:
    jobs:
      - maven/test:
          command: '-X compile'
          executor: java17
ESTE COMMIT HA SIDO ROTO POR JUAN, CULPEN A JUAN
